/**
 * Static import map for Phosphor Svelte icons used in TagFilter.
 * Imported lazily (via dynamic import in TagFilter) so the barrel file
 * is never scanned during Astro SSR — only loaded on the client.
 */

import {
  AmbulanceIcon,
  AirplaneIcon,
  AnchorIcon,
  AvocadoIcon,
  BabyIcon,
  BackpackIcon,
  BalloonIcon,
  BasketballIcon,
  BathtubIcon,
  BedIcon,
  BellIcon,
  BicycleIcon,
  BirdIcon,
  BoatIcon,
  BoneIcon,
  BookIcon,
  BreadIcon,
  BusIcon,
  ButterflyIcon,
  CakeIcon,
  CameraIcon,
  CarIcon,
  CarrotIcon,
  CatIcon,
  CheeseIcon,
  CircleIcon,
  CloudIcon,
  CompassIcon,
  ConfettiIcon,
  CookieIcon,
  CowIcon,
  CrownIcon,
  CubeIcon,
  DiamondIcon,
  DogIcon,
  EarIcon,
  EggIcon,
  EraserIcon,
  EyeIcon,
  FireIcon,
  FishIcon,
  FlagIcon,
  FlowerIcon,
  ForkKnifeIcon,
  GiftIcon,
  GlobeIcon,
  GuitarIcon,
  HamburgerIcon,
  HandIcon,
  HeartIcon,
  HorseIcon,
  HouseIcon,
  IceCreamIcon,
  IslandIcon,
  LeafIcon,
  LightningIcon,
  MicrophoneIcon,
  MoonIcon,
  MotorcycleIcon,
  MusicNoteIcon,
  NumberSquareOneIcon,
  OrangeIcon,
  PaletteIcon,
  PaintBrushIcon,
  PawPrintIcon,
  PencilIcon,
  PepperIcon,
  PizzaIcon,
  PlantIcon,
  RabbitIcon,
  RainbowIcon,
  RobotIcon,
  RocketIcon,
  RulerIcon,
  ScissorsIcon,
  ShrimpIcon,
  SmileyIcon,
  SnowflakeIcon,
  SoccerBallIcon,
  SparkleIcon,
  SquareIcon,
  StarIcon,
  SunIcon,
  TagIcon,
  ToothIcon,
  TractorIcon,
  TrainIcon,
  TreeIcon,
  TriangleIcon,
  TruckIcon,
  UmbrellaIcon,
  VolleyballIcon,
  WindIcon
} from 'phosphor-svelte';

export const SVELTE_ICON_MAP: Record<string, any> = {
  Ambulance: AmbulanceIcon,
  Airplane: AirplaneIcon,
  Anchor: AnchorIcon,
  Avocado: AvocadoIcon,
  Baby: BabyIcon,
  Backpack: BackpackIcon,
  Balloon: BalloonIcon,
  Basketball: BasketballIcon,
  Bathtub: BathtubIcon,
  Bed: BedIcon,
  Bell: BellIcon,
  Bicycle: BicycleIcon,
  Bird: BirdIcon,
  Boat: BoatIcon,
  Bone: BoneIcon,
  Book: BookIcon,
  Bread: BreadIcon,
  Bus: BusIcon,
  Butterfly: ButterflyIcon,
  Cake: CakeIcon,
  Camera: CameraIcon,
  Car: CarIcon,
  Carrot: CarrotIcon,
  Cat: CatIcon,
  Cheese: CheeseIcon,
  Circle: CircleIcon,
  Cloud: CloudIcon,
  Compass: CompassIcon,
  Confetti: ConfettiIcon,
  Cookie: CookieIcon,
  Cow: CowIcon,
  Crown: CrownIcon,
  Cube: CubeIcon,
  Diamond: DiamondIcon,
  Dog: DogIcon,
  Ear: EarIcon,
  Egg: EggIcon,
  Eraser: EraserIcon,
  Eye: EyeIcon,
  Fire: FireIcon,
  Fish: FishIcon,
  Flag: FlagIcon,
  Flower: FlowerIcon,
  ForkKnife: ForkKnifeIcon,
  Gift: GiftIcon,
  Globe: GlobeIcon,
  Guitar: GuitarIcon,
  Hamburger: HamburgerIcon,
  Hand: HandIcon,
  Heart: HeartIcon,
  Horse: HorseIcon,
  House: HouseIcon,
  IceCream: IceCreamIcon,
  Island: IslandIcon,
  Leaf: LeafIcon,
  Lightning: LightningIcon,
  Microphone: MicrophoneIcon,
  Moon: MoonIcon,
  Motorcycle: MotorcycleIcon,
  MusicNote: MusicNoteIcon,
  NumberSquareOne: NumberSquareOneIcon,
  Orange: OrangeIcon,
  Palette: PaletteIcon,
  PaintBrush: PaintBrushIcon,
  PawPrint: PawPrintIcon,
  Pencil: PencilIcon,
  Pepper: PepperIcon,
  Pizza: PizzaIcon,
  Plant: PlantIcon,
  Rabbit: RabbitIcon,
  Rainbow: RainbowIcon,
  Robot: RobotIcon,
  Rocket: RocketIcon,
  Ruler: RulerIcon,
  Scissors: ScissorsIcon,
  Shrimp: ShrimpIcon,
  Smiley: SmileyIcon,
  Snowflake: SnowflakeIcon,
  SoccerBall: SoccerBallIcon,
  Sparkle: SparkleIcon,
  Square: SquareIcon,
  Star: StarIcon,
  Sun: SunIcon,
  Tag: TagIcon,
  Tooth: ToothIcon,
  Tractor: TractorIcon,
  Train: TrainIcon,
  Tree: TreeIcon,
  Triangle: TriangleIcon,
  Truck: TruckIcon,
  Umbrella: UmbrellaIcon,
  Volleyball: VolleyballIcon,
  Wind: WindIcon,
};
